### ISSUE TITLE
KeyError in waytype meansoftransport

### ISSUE THREAD

**Issue by nonchip** [NoMoKeTo/transit#2]
```
$ ./transit --pretty vrr - <<<'["Trip.Request", {"origin": ["Stop", {"city": "hamburg", "name": "hbf"}], "destination": ["Stop", {"city": "essen", "name": "hbf"}]}]'                                                    
Traceback (most recent call last):
  File "./transit", line 2, in <module>
    import cli
  File "/home/kyra/transit/cli.py", line 43, in <module>
    result = network.query(search)
  File "/home/kyra/transit/apis/base.py", line 18, in query
    return self.search_trip(obj)
  File "/home/kyra/transit/apis/base.py", line 43, in search_trip
    return self._search_trips(obj)
  File "/home/kyra/transit/apis/efa.py", line 34, in _search_trips
    return self._trip_request(triprequest)
  File "/home/kyra/transit/apis/efa.py", line 219, in _trip_request
    results = Trip.Results(self._parse_routes(data.find('./itdItinerary/itdRouteList')))
  File "/home/kyra/transit/apis/efa.py", line 579, in _parse_routes
    part = self._parse_routepart(routepart)
  File "/home/kyra/transit/apis/efa.py", line 681, in _parse_routepart
    waytype = {'100': 'walk', '101': 'bike', '104': 'car', '105': 'taxi'}[data.find('./itdMeansOfTransport').attrib['type']]
KeyError: '98'
```

I'll send in a patch.

**Comment by NoMoKeTo** [comment]
Fixed in 014b6ec80e321eb3b9f0105cf2a130ee4aba9fac
